### ISSUE TITLE
how to load data

### ISSUE THREAD

**Issue by amir-tagh** [mcsorkun/ChemPlot#9]
Hello,

thanks for this great set of tools. I was going through the tutorials from https://chemplot.readthedocs.io/en/latest/api.html
putting everything in a python script but I couldn't figure out how to load local data sets using something similar to load_data function?
and also do you have any plans to add some other properties like radar charts to this set.

Thanks,
Amir

**Comment by dajtmullaj** [comment]
Hello @amir-tagh,
our `load_data` function only loads one of the [sample datasets](https://chemplot.readthedocs.io/en/latest/user_manual/sample_datasets.html) we provide with the library.
Therefore how to load your data is very dependent on how your local data is stored locally. If it is a csv file you can use `pandas.read_csv` to import it as a dataframe. 
What is important for ChemPlot is only to have a collection type instance fed as the SMILES parameter or target.

**Comment by dajtmullaj** [comment]
As an example:
```
from pandas import read_csv

loaded_data = read_csv("local_data.csv")
```

I updated the *getting started* section of the docs to reflect this example as the `load_data` function I understand can be confusing. I hope this clarifies! 
Regarding different plots, we might add some in the future if we think the community will benefit from them and if they add value that the current plots cannot express. A radar chart might be a bit complicated since you need to decide which properties to put along the radar, and there might not be a general answer for that. Solutions can be explored (letting the properties be targets selected by the user), depending on the need we feel the community has for a given plot!

Let us know if you encounter any other problems! 
I will be closing the issue for now.
